minimumReleaseAgeExclude:
  - eslint@10.5.0

shellEmulator: true

trustPolicy: no-downgrade

overrides:
  semver@5.7.2: ^7.8.4

allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true
  simple-git-hooks: true
